--- 
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Deploy script"
        uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
name: "Deploy to Bookstack"
true: 
  push: 
    branches: 
      - master