name: Deploy to Bookstack

on:
  push:
    branches:
      - master
      
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: whoami
          host: 37.46.85.14
          username: bookstack
          password: ${{ secrets.PASSWORD }}